[package]
name = "demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.193"
chrono = "0.4.31"
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
